dist: trusty
language: c
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - llvm-4.0-dev

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_FAHRENHEIT_TESTS=1 .
  - make 
  - make test

notifications:
  email: false

