dist: trusty
language: c
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - lua5.2

before_install:
  - wget http://releases.llvm.org/3.9.1/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - unxz clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar xfv clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar
  - mv clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04 llvm

script:
  - export fahrenheit_dir=`pwd`; export llvm_dir=`pwd`/llvm/lib/cmake/llvm
  - mkdir build; cd build
  - cmake -DLLVM_DIR="${llvm_dir}" ..
  - make 
  - cd ${fahrenheit_dir}/examples
  - mkdir build; cd build
  - cmake -DLLVM_DIR="${llvm_dir}" ..
  - make
  - cd ${fahrenheit_dir}/tests
  - mkdir build; cd build
  - cmake -DLLVM_DIR="${llvm_dir}" ..
  - make 
  - make test

notifications:
  email: false

