dist: trusty
language: c
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - llvm-3.8-dev

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_FAHRENHEIT_TESTS=1 \
    -DLLVM_DIR=/usr/lib/llvm-3.8/cmake .
  - make 
  - make test

notifications:
  email: false

