Fahrenheit module
.
module with no functions
----------------------------------------
Fahrenheit module
function @01 : void -> void
 bb1

.
error at function 1, basic block 1:
basic block not terminated
----------------------------------------
Fahrenheit module
function @01 : void -> void
 bb1
         ret void
         ret void

.
error at function 1, basic block 1, instruction 1:
instruction after basic block end
----------------------------------------
Fahrenheit module
function @01 : void -> void
 bb1
         ret (const i64 123)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret void

.
error at function 1, basic block 1, instruction 1:
null value
----------------------------------------
Fahrenheit module
function @01 : void -> void
 bb1
         ret void

.
ok
running function @1 with 
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const bool true)

.
ok
running function @1 with 
1
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> bool
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const i8 255)

.
ok
running function @1 with 
255
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i8
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const i16 1234)

.
ok
running function @1 with 
1234
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i16
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const i32 12345)

.
ok
running function @1 with 
12345
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i32
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const i64 123456)

.
ok
running function @1 with 
123456
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> i64
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const flt 123.450000)

.
ok
running function @1 with 
123.45
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> flt
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const dbl 12345.567890)

.
ok
running function @1 with 
12345.6
----------------------------------------
Fahrenheit module
function @01 : void -> dbl
 bb1
         ret (const ptr ptr)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const bool true)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const i8 255)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const i16 1234)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const i32 12345)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const i64 123456)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const flt 123.450000)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const dbl 12345.567890)

.
error at function 1, basic block 1, instruction 1:
return type missmatch
----------------------------------------
Fahrenheit module
function @01 : void -> ptr
 bb1
         ret (const ptr ptr)

.
ok
running function @1 with 
1
----------------------------------------
Number of tests cases: 70
